
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl;
    listen [::]:8443 ssl;

    server_name _;

    ssl_certificate     /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # Baseline volontairement faible
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'HIGH:MEDIUM:!aNULL:!MD5';
    ssl_prefer_server_ciphers on;

    root /var/www/html;
    index index.html;
}

